package App::Switchable::File;

use Carp;

require Exporter;
our @ISA = qw<Exporter>;


=head1 NAME

App::Switchable::File

=head1 SYNOPSIS

 # In App::Switchable
 require App::Switchable::File;
 our @ISA = qw< App::Switchable::File >;
 
 $self->write_aliases;

=head1 DESCRIPTION

This module handles file creation, edition, and parsing. Configuration files are handles by L<App::Switchable::Config>.

=cut

=head1 METHODS

=head2 $app->write_aliases

Write the aliases from the config to the filesystem

=cut

sub write_aliases {
	my $self = shift;
	
	my $string;
	$string .= "# Generated by switchable, modifications will be overwritten\n\n";
	foreach my $alias ($self->config->{alias}->@*) {
		$alias =~ s/'/'\\''/g;
		$string .= qq(alias '$alias'="DRI_PRIME=1 $alias"\n);
	}
	$string .= "# End of file";
	
	$self->aliases_file->touchpath or croak "Could not create aliases file at ".$self->aliases_file;
	$self->aliases_file->spew($string);
}

1;
